import type { PlayDeckTemplate } from "./types";

/**
 * Large built-in library of optional fun / unwind / challenge missions (Dutch copy).
 * Matched against play_profile via tags + free-text keywords in score-play-templates.ts
 */
export const PLAY_DECK_TEMPLATES: PlayDeckTemplate[] = [
  { id: "pd_u01", title: "Luister één nummer volledig, telefoon op vliegtuigstand.", play_kind: "unwind", tags: ["quiet", "music"], energy: 1 },
  { id: "pd_u02", title: "5 minuten alleen ademen bij het raam.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_u03", title: "Warme drank, geen scherm, 10 minuten.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_u04", title: "Korte bodyscan: tenen tot kruin, in je tempo.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_u05", title: "Schrijf drie dingen op die vandaag oké gingen.", play_kind: "unwind", tags: ["quiet", "creative"], energy: 1 },
  { id: "pd_u06", title: "Lees 5 pagina’s van iets dat geen nieuws is.", play_kind: "unwind", tags: ["quiet", "reading"], energy: 1 },
  { id: "pd_u07", title: "Neem een bad of extra lange douche, muziekje mag.", play_kind: "unwind", tags: ["quiet", "music"], energy: 2 },
  { id: "pd_u08", title: "Trek warme sokken aan en niets ‘nuttigs’ doen — 15 min.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_u09", title: "Mini-dagboek: één zin over hoe je je nu voelt.", play_kind: "unwind", tags: ["quiet", "creative"], energy: 1 },
  { id: "pd_u10", title: "Sta op, rek uit, rol schouders — 3 rondjes.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_u11", title: "Kijk bewust uit het raam: tel 10 verschillende kleuren.", play_kind: "unwind", tags: ["quiet", "nature"], energy: 1 },
  { id: "pd_u12", title: "Zet één kamer op soft licht, alleen sfeer.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_f01", title: "Dans op één lied in de woonkamer (niemand kijkt).", play_kind: "fun", tags: ["music", "active"], energy: 2 },
  { id: "pd_f02", title: "Maak een 5-minuten playlist ‘alleen voor mij’.", play_kind: "fun", tags: ["music", "creative"], energy: 1 },
  { id: "pd_f03", title: "Teken een krabbeltje van je dag als strip van 3 panelen.", play_kind: "fun", tags: ["creative", "chill"], energy: 2 },
  { id: "pd_f04", title: "Bouw iets doms van LEGO of stapel blokjes — 10 min.", play_kind: "fun", tags: ["games", "creative"], energy: 2 },
  { id: "pd_f05", title: "Speel één level / één potje van je chillste game.", play_kind: "fun", tags: ["games", "chill"], energy: 2 },
  { id: "pd_f06", title: "Bak iets simpels (koek / toast / mug cake).", play_kind: "fun", tags: ["cooking", "creative"], energy: 2 },
  { id: "pd_f07", title: "Kook met alleen ingrediënten die je al hebt — mini-challenge.", play_kind: "fun", tags: ["cooking", "competitive"], energy: 3, spice: "medium" },
  { id: "pd_f08", title: "Maak een foto van iets lelijks-schoons in huis.", play_kind: "fun", tags: ["creative", "chill"], energy: 1 },
  { id: "pd_f09", title: "Bekijk één aflevering van iets dat je al kent — comfort rewatch.", play_kind: "fun", tags: ["film", "chill"], energy: 2 },
  { id: "pd_f10", title: "Hum je favoriete deuntje en laat iemand raden (of voice memo).", play_kind: "fun", tags: ["music", "social_light"], energy: 2 },
  { id: "pd_f11", title: "Maak een papieren vliegtuigje; beste afstand wint (solo mag ook).", play_kind: "fun", tags: ["games", "creative"], energy: 1 },
  { id: "pd_f12", title: "Zoek 3 memes die je echt laten lachen — opslaan voor later.", play_kind: "fun", tags: ["games", "chill"], energy: 1 },
  { id: "pd_f13", title: "Speel 10 minuten een instrument, geen oefenplan, alleen spelen.", play_kind: "fun", tags: ["music", "creative"], energy: 2 },
  { id: "pd_f14", title: "Doe een stomme voice voor je eigen voicemail — niet opslaan is oké.", play_kind: "fun", tags: ["creative", "social_light"], energy: 2 },
  { id: "pd_f15", title: "Kies een podcast-fragment van 15 min en wandelen terwijl je luistert.", play_kind: "fun", tags: ["outdoors", "music"], energy: 2 },
  { id: "pd_c01", title: "Timer 7 min: zo veel mogelijk stappen in huis.", play_kind: "challenge", tags: ["active", "sports"], energy: 2, spice: "medium" },
  { id: "pd_c02", title: "Plank 20 seconden × 3, met pauze.", play_kind: "challenge", tags: ["sports", "competitive"], energy: 2, spice: "medium" },
  { id: "pd_c03", title: "Timer 2 min: naam 20 dingen in de kamer die blauw/groen zijn.", play_kind: "challenge", tags: ["puzzles", "competitive"], energy: 1, spice: "low" },
  { id: "pd_c04", title: "Maak een woord met letters van boodschappenbon — langste woord wint.", play_kind: "challenge", tags: ["puzzles", "shopping"], energy: 1, spice: "medium" },
  { id: "pd_c05", title: "20 push-ups op delen (mag op knieën): alleen voltooien telt.", play_kind: "challenge", tags: ["sports", "competitive"], energy: 3, spice: "high" },
  { id: "pd_c06", title: "Eén ronde memory met een deck kaarten — tijd noteren.", play_kind: "challenge", tags: ["games", "puzzles"], energy: 2, spice: "medium" },
  { id: "pd_c07", title: "Sudoku / kruiswoord: 10 minuten focus, geen hints.", play_kind: "challenge", tags: ["puzzles", "quiet"], energy: 2, spice: "low" },
  { id: "pd_c08", title: "Leer 5 woorden in een taal die je cool vindt — quiz jezelf.", play_kind: "challenge", tags: ["reading", "competitive"], energy: 2, spice: "medium" },
  { id: "pd_o01", title: "10 minuten wandelen zonder bestemming, andere straat dan gisteren.", play_kind: "unwind", tags: ["outdoors", "quiet"], energy: 2 },
  { id: "pd_o02", title: "Zoek één mooi blad of steen en leg die op je bureau.", play_kind: "fun", tags: ["outdoors", "nature"], energy: 1 },
  { id: "pd_o03", title: "Balkon/tuin: 5 minuten wolken kijken.", play_kind: "unwind", tags: ["outdoors", "nature", "quiet"], energy: 1 },
  { id: "pd_o04", title: "Fiets rondje: alleen voor het gevoel, geen Strava-record.", play_kind: "fun", tags: ["outdoors", "sports"], energy: 3 },
  { id: "pd_s01", title: "Stuur iemand een voice: ‘ik dacht aan je’ — kort.", play_kind: "fun", tags: ["social_light"], energy: 2 },
  { id: "pd_s02", title: "Bel 5 min met iemand zonder agenda.", play_kind: "unwind", tags: ["social_light", "quiet"], energy: 2 },
  { id: "pd_s03", title: "Schrijf een briefkaart of DM met één inside joke.", play_kind: "fun", tags: ["social_light", "creative"], energy: 2 },
  { id: "pd_s04", title: "Co-op game: één level samen (online of lokaal).", play_kind: "fun", tags: ["games", "social_light"], energy: 2 },
  { id: "pd_p01", title: "5 minuten spelen met je huisdier, telefoon weg.", play_kind: "fun", tags: ["pets", "active"], energy: 2 },
  { id: "pd_p02", title: "Nieuwe route wandelen met de hond (of ‘alsof’ je een hond hebt).", play_kind: "fun", tags: ["pets", "outdoors"], energy: 2 },
  { id: "pd_p03", title: "Maak een hide-and-seek snack trail voor je kat/hond.", play_kind: "fun", tags: ["pets", "games"], energy: 2 },
  { id: "pd_g01", title: "Grote boodschap: beloon jezelf achteraf met iets kleins lekkers.", play_kind: "unwind", tags: ["shopping", "chill"], energy: 2 },
  { id: "pd_g02", title: "Kleine boodschap: timed run — binnen 15 min in en uit.", play_kind: "challenge", tags: ["shopping", "competitive"], energy: 2, spice: "medium" },
  { id: "pd_g03", title: "Eén nieuw ingrediënt meenemen dat je nog nooit kocht.", play_kind: "fun", tags: ["shopping", "cooking"], energy: 2 },
  { id: "pd_g04", title: "Boodschappenlijst op ritme van een liedje zingen.", play_kind: "fun", tags: ["shopping", "music"], energy: 1 },
  { id: "pd_r01", title: "Herlees een favoriet hoofdstuk — max 15 pagina’s.", play_kind: "unwind", tags: ["reading", "quiet"], energy: 1 },
  { id: "pd_r02", title: "Lees hardop één gedicht of songtekst.", play_kind: "fun", tags: ["reading", "music"], energy: 1 },
  { id: "pd_cr1", title: "Brei/hakkel één rij zonder multitasken.", play_kind: "unwind", tags: ["crafting", "quiet"], energy: 1 },
  { id: "pd_cr2", title: "Kleur binnen de lijnen — 10 minuten kind-niveau mag.", play_kind: "unwind", tags: ["creative", "chill"], energy: 1 },
  { id: "pd_cr3", title: "Maak een collage van oude magazines of prints.", play_kind: "fun", tags: ["creative", "crafting"], energy: 2 },
  { id: "pd_n01", title: "Identificeer 3 vogels of bomen via app — alleen nieuwsgierigheid.", play_kind: "fun", tags: ["nature", "puzzles"], energy: 2 },
  { id: "pd_n02", title: "Plant water geven + 1 min compliment tegen het blad.", play_kind: "fun", tags: ["nature", "chill"], energy: 1 },
  { id: "pd_x01", title: "Speedrun opruimen één la — 5 minuten timer.", play_kind: "challenge", tags: ["competitive", "quiet"], energy: 2, spice: "low" },
  { id: "pd_x02", title: "Maak je bed ‘hotel-style’ — alleen voor het gevoel.", play_kind: "unwind", tags: ["chill", "quiet"], energy: 1 },
  { id: "pd_x03", title: "Zet een timer: dans door je huis tussen twee kamers.", play_kind: "fun", tags: ["active", "music"], energy: 2 },
  { id: "pd_x04", title: "Kies een oude foto en vertel die hardop in 30 seconden.", play_kind: "fun", tags: ["creative", "social_light"], energy: 1 },
  { id: "pd_x05", title: "Maak thee/koffie alsof het een ritueel is — traag.", play_kind: "unwind", tags: ["chill", "cooking"], energy: 1 },
  { id: "pd_x06", title: "Leg een korte puzzel: alleen randjes eerst, 10 min max.", play_kind: "challenge", tags: ["puzzles", "quiet"], energy: 2, spice: "low" },
  { id: "pd_x07", title: "Schrijf een bucketlist van 5 domme kleine dingen voor dit jaar.", play_kind: "fun", tags: ["creative", "chill"], energy: 1 },
  { id: "pd_x08", title: "Doe één goede daad anoniem (postits, compliment, kleine gift).", play_kind: "fun", tags: ["social_light", "chill"], energy: 2 },
  { id: "pd_x09", title: "Mini-karaoke: één refrein op volume dat buren niet bellen.", play_kind: "fun", tags: ["music", "competitive"], energy: 2, spice: "low" },
  { id: "pd_x10", title: "Bouw de hoogste stapeltje munten in 1 minuut.", play_kind: "challenge", tags: ["games", "competitive"], energy: 1, spice: "medium" },
  { id: "pd_x11", title: "Zoek een willekeurig Wikipedia-artikel — lees de inleiding.", play_kind: "fun", tags: ["reading", "puzzles"], energy: 1 },
  { id: "pd_x12", title: "Maak een ‘vakantie in huis’ hoek met kussen en lamp.", play_kind: "unwind", tags: ["chill", "creative"], energy: 2 },
  { id: "pd_x13", title: "Timer: zo snel mogelijk 20 objecten terugleggen op hun plek.", play_kind: "challenge", tags: ["competitive", "quiet"], energy: 2, spice: "medium" },
  { id: "pd_x14", title: "Speel statues: 2 min stil staan — eerste die beweegt lacht.", play_kind: "fun", tags: ["games", "social_light"], energy: 1 },
  { id: "pd_x15", title: "Schrijf een limerick over je week.", play_kind: "fun", tags: ["creative", "reading"], energy: 2, spice: "low" },
  { id: "pd_x16", title: "Doe een ‘blind proeven’ van 3 snacks uit de kast.", play_kind: "fun", tags: ["cooking", "games"], energy: 1 },
  { id: "pd_x17", title: "Maak een fort van dekens — 10 min lezen erin.", play_kind: "unwind", tags: ["reading", "creative", "chill"], energy: 2 },
  { id: "pd_x18", title: "Eén ronde kaarten tegen jezelf (solitaire) — snelste tijd.", play_kind: "challenge", tags: ["games", "puzzles"], energy: 2, spice: "low" },
  { id: "pd_x19", title: "Wandel naar de winkel zonder oordopjes — omgeving geluid.", play_kind: "unwind", tags: ["outdoors", "shopping", "quiet"], energy: 2 },
  { id: "pd_x20", title: "Teken je ideale zondag in stick figures.", play_kind: "fun", tags: ["creative", "chill"], energy: 1 },
  { id: "pd_x21", title: "Maak een ‘niet storen’-bord voor jezelf — creatief.", play_kind: "fun", tags: ["creative", "quiet"], energy: 1 },
  { id: "pd_x22", title: "Doe 30 jumping jacks — liedje erbij.", play_kind: "challenge", tags: ["sports", "music"], energy: 2, spice: "medium" },
  { id: "pd_x23", title: "Schrijf 10 woorden die je aan vreugde linken — snelste lijst.", play_kind: "unwind", tags: ["creative", "quiet"], energy: 1 },
  { id: "pd_x24", title: "Bekijk trailers van 3 films die je nooit kijkt — kies één voor later.", play_kind: "fun", tags: ["film", "games"], energy: 1 },
  { id: "pd_x25", title: "Maak een mini-toernooi: steen-papier-schaar best of 5 met jezelf.", play_kind: "fun", tags: ["games", "chill"], energy: 1 },
  { id: "pd_x26", title: "Organiseer één la ‘arcade style’ high scores (meeste spullen weg).", play_kind: "challenge", tags: ["competitive", "quiet"], energy: 3, spice: "medium" },
  { id: "pd_x27", title: "Zing in de auto/douche: volledige playback, geen schaamte.", play_kind: "fun", tags: ["music", "chill"], energy: 2 },
  { id: "pd_x28", title: "Maak een ‘comfort kit’ doos: thee, boek, sokken.", play_kind: "unwind", tags: ["chill", "reading"], energy: 2 },
  { id: "pd_x29", title: "Willekeurige dans-move generator: doe 5 moves achter elkaar.", play_kind: "fun", tags: ["active", "games"], energy: 2 },
  { id: "pd_x30", title: "Schrijf een review van je dag alsof het een game is (sterren + pros/cons).", play_kind: "fun", tags: ["creative", "games"], energy: 2 },
];
