import type { PlayDeckTemplate } from "./types";

/** Extra library entries (ids pd_e*) — merged into PLAY_DECK_TEMPLATES */
export const PLAY_DECK_TEMPLATES_EXTRA: PlayDeckTemplate[] = [
  { id: "pd_e01", title: "Schrijf 6 regels fictie: eerste zin begint met ‘Het was te warm voor…’", play_kind: "fun", tags: ["writing", "creative", "quiet"], energy: 2 },
  { id: "pd_e02", title: "Foto-serie: 5 hoeken in huis die je normaal negeert.", play_kind: "fun", tags: ["photography", "creative", "homebody"], energy: 2 },
  { id: "pd_e03", title: "Leer één zin in een taal die je cool vindt — hardop.", play_kind: "challenge", tags: ["learning", "competitive"], energy: 2, spice: "low" },
  { id: "pd_e04", title: "Podcast-snippet 8 min: alleen luisteren, geen multitask.", play_kind: "unwind", tags: ["podcasts", "quiet", "music"], energy: 1 },
  { id: "pd_e05", title: "Dans-choreo: 3 moves, herhaal 5× op je favoriete refrein.", play_kind: "fun", tags: ["dancing", "music", "active"], energy: 2 },
  { id: "pd_e06", title: "Bordspel solo-variant: één beurt van je favoriete spel simuleren.", play_kind: "fun", tags: ["boardgames", "puzzles", "games"], energy: 2 },
  { id: "pd_e07", title: "Maak een tier-list van snacks in huis (S tot F).", play_kind: "fun", tags: ["games", "cooking", "chill"], energy: 1 },
  { id: "pd_e08", title: "Vouw iets nutteloos-schoons (servet, verpakking, technische vouw) — tutorial mag.", play_kind: "unwind", tags: ["crafting", "quiet", "creative"], energy: 1 },
  { id: "pd_e09", title: "Plant-ronde: stof af, draaien, compliment.", play_kind: "unwind", tags: ["nature", "chill", "homebody"], energy: 1 },
  { id: "pd_e10", title: "‘Fake window’: zet video van regen/bos op TV 10 min.", play_kind: "unwind", tags: ["nature", "film", "quiet"], energy: 1 },
  { id: "pd_e11", title: "Speed-clean één oppervlak: 4 min timer, alleen dat.", play_kind: "challenge", tags: ["competitive", "homebody"], energy: 2, spice: "low" },
  { id: "pd_e12", title: "Maak een playlist ‘ochtend’ of ‘avond’ met exact 8 nummers.", play_kind: "fun", tags: ["music", "creative"], energy: 1 },
  { id: "pd_e13", title: "Still life: teken of fotografeer je favoriete mok zonder filter.", play_kind: "fun", tags: ["creative", "photography", "chill"], energy: 1 },
  { id: "pd_e14", title: "Mini-workout: wall sit 20s × 3.", play_kind: "challenge", tags: ["sports", "competitive"], energy: 2, spice: "medium" },
  { id: "pd_e15", title: "Loop trappen op en af tot een liedje klaar is.", play_kind: "fun", tags: ["active", "music", "sports"], energy: 2 },
  { id: "pd_e16", title: "Schrijf een brief aan je toekomstige zelf over deze week (1 kant).", play_kind: "unwind", tags: ["writing", "quiet"], energy: 2 },
  { id: "pd_e17", title: "Bak/brew: experimenteer met kruiden in thee of koffie.", play_kind: "fun", tags: ["cooking", "creative"], energy: 1 },
  { id: "pd_e18", title: "Zoek 3 Wikipedia-rabbit-holes — alleen de eerste alinea.", play_kind: "fun", tags: ["learning", "reading", "puzzles"], energy: 2 },
  { id: "pd_e19", title: "Kies 3 voorwerpen die ‘jou als expositie’ zouden zijn — noteer titels op kaartje.", play_kind: "fun", tags: ["creative", "homebody", "philosophy"], energy: 2 },
  { id: "pd_e20", title: "Stille disco: 2 nummers met oordopjes, overdreven meezingen.", play_kind: "fun", tags: ["music", "chill"], energy: 2 },
  { id: "pd_e21", title: "Buiten: tel 12 verschillende geluiden.", play_kind: "unwind", tags: ["outdoors", "quiet", "nature"], energy: 2 },
  { id: "pd_e22", title: "Maak een ‘dagelijkse quest’ kaartje voor morgen (1 zin).", play_kind: "fun", tags: ["games", "creative"], energy: 1 },
  { id: "pd_e23", title: "Rek je tenen — serieus — 1 min per voet.", play_kind: "unwind", tags: ["chill", "sports"], energy: 1 },
  { id: "pd_e24", title: "Kook één gerecht met 3 ingrediënten max (zout/peper gratis).", play_kind: "challenge", tags: ["cooking", "competitive"], energy: 3, spice: "medium" },
  { id: "pd_e25", title: "Schrijf een parodie-opener van je favoriete serie.", play_kind: "fun", tags: ["writing", "film", "creative"], energy: 2 },
  { id: "pd_e26", title: "Sorteer 10 boeken of games op kleur of dikte — timer 6 min.", play_kind: "challenge", tags: ["games", "homebody", "competitive"], energy: 2, spice: "low" },
  { id: "pd_e27", title: "Meditatie-body-scan alleen voor je handen — 4 min.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_e28", title: "Maak een collage op je koelkast met 4 post-its.", play_kind: "fun", tags: ["creative", "crafting"], energy: 1 },
  { id: "pd_e29", title: "Wandeling: foto van iets geometrisch in de straat.", play_kind: "fun", tags: ["outdoors", "photography", "creative"], energy: 2 },
  { id: "pd_e30", title: "Leer een kaarttruc van een video — alleen de eerste move.", play_kind: "challenge", tags: ["learning", "games"], energy: 2, spice: "low" },
  { id: "pd_e31", title: "Schrijf synoniemen-rondje: ‘moe’ 8 andere woorden.", play_kind: "fun", tags: ["writing", "puzzles"], energy: 1 },
  { id: "pd_e32", title: "Doe alsof je een slow-TV aflevering presenteert over je kamer.", play_kind: "fun", tags: ["film", "creative", "silly"], energy: 2 },
  { id: "pd_e33", title: "Yoga-light: 5× flow / zonnegroet in je eigen tempo.", play_kind: "unwind", tags: ["sports", "chill", "quiet"], energy: 2 },
  { id: "pd_e34", title: "Maak een ‘high score’ in aantal stappen van bank naar koelkast.", play_kind: "challenge", tags: ["competitive", "games"], energy: 1, spice: "low" },
  { id: "pd_e35", title: "Lees een willekeurig recept hardop als ASMR.", play_kind: "fun", tags: ["cooking", "reading", "chill"], energy: 1 },
  { id: "pd_e36", title: "Teken kaart van je buurt uit het hoofd — fouten mogen.", play_kind: "fun", tags: ["creative", "puzzles", "outdoors"], energy: 2 },
  { id: "pd_e37", title: "Silhouet voor het raam: één dramatische foto van jezelf (geen gezicht nodig).", play_kind: "fun", tags: ["photography", "creative", "film"], energy: 1 },
  { id: "pd_e38", title: "Schrijf bucketlist van 10 dingen onder €5.", play_kind: "fun", tags: ["writing", "creative"], energy: 2 },
  { id: "pd_e39", title: "Ontdek één nieuw woord in je moedertaal en gebruik het 3× vandaag.", play_kind: "challenge", tags: ["learning", "competitive"], energy: 2, spice: "low" },
  { id: "pd_e40", title: "Maak thee met timer: 4 min precies steep time.", play_kind: "unwind", tags: ["cooking", "quiet", "chill"], energy: 1 },
  { id: "pd_e41", title: "Foto van reflectie (raam, plas, lepel) — artist mode.", play_kind: "fun", tags: ["photography", "creative"], energy: 2 },
  { id: "pd_e42", title: "Doe een ‘outfit check’ alsof je een streamer bent — 30 sec.", play_kind: "fun", tags: ["silly", "social_light"], energy: 1 },
  { id: "pd_e43", title: "Bouw hoogste toren van blikjes/boeken in 2 min.", play_kind: "challenge", tags: ["competitive", "games", "homebody"], energy: 2, spice: "medium" },
  { id: "pd_e44", title: "Luister één album track-by-track, geen skip.", play_kind: "unwind", tags: ["music", "quiet"], energy: 2 },
  { id: "pd_e45", title: "Schrijf ‘liner notes’ voor een playlist die nog niet bestaat.", play_kind: "fun", tags: ["writing", "music"], energy: 2 },
  { id: "pd_e46", title: "Mini-picknick op de grond: snack + deken.", play_kind: "fun", tags: ["cooking", "chill", "creative"], energy: 2 },
  { id: "pd_e47", title: "Tel voorwerpen in één kleur in de kamer — snelste tijd.", play_kind: "challenge", tags: ["puzzles", "competitive"], energy: 1, spice: "low" },
  { id: "pd_e48", title: "Maak een ‘soundtrack’ van je week met 5 songtitels.", play_kind: "fun", tags: ["music", "writing", "creative"], energy: 2 },
  { id: "pd_e49", title: "Stretch-hamstrings: 90s per been, adem rustig.", play_kind: "unwind", tags: ["sports", "quiet", "chill"], energy: 1 },
  { id: "pd_e50", title: "Speel ‘wat zit er in de doos?’ met een tas en random voorwerp.", play_kind: "fun", tags: ["games", "silly"], energy: 1 },
  { id: "pd_e51", title: "Lees de ingrediënten van 3 verpakkingen als poëzie.", play_kind: "fun", tags: ["reading", "silly", "creative"], energy: 1 },
  { id: "pd_e52", title: "Wandel zonder telefoon 12 min — route in L-vorm.", play_kind: "unwind", tags: ["outdoors", "quiet"], energy: 2 },
  { id: "pd_e53", title: "Maak een zin met woorden van 3 producten in je koelkast.", play_kind: "fun", tags: ["cooking", "puzzles", "writing"], energy: 1 },
  { id: "pd_e54", title: "Teken je hand 2×: links/rechts dominante vergelijking.", play_kind: "fun", tags: ["creative", "quiet"], energy: 1 },
  { id: "pd_e55", title: "Doe 1 minuut ‘grappige loop’ door je gang.", play_kind: "fun", tags: ["silly", "active", "chill"], energy: 2 },
  { id: "pd_e56", title: "Schrijf 3 zinnen ‘liefdevolle roast’ over één object in huis.", play_kind: "fun", tags: ["writing", "silly", "chill"], energy: 1 },
  { id: "pd_e57", title: "Zoek de oudste foto op je telefoon en vertel die in 20 sec.", play_kind: "fun", tags: ["social_light", "creative"], energy: 1 },
  { id: "pd_e58", title: "Maak een ‘boss fight’ playlist van 3 nummers voor afwas.", play_kind: "fun", tags: ["music", "games", "cooking"], energy: 2 },
  { id: "pd_e59", title: "Balanceer iets op je hoofd 20 stappen.", play_kind: "challenge", tags: ["sports", "silly", "competitive"], energy: 2, spice: "medium" },
  { id: "pd_e60", title: "Lees voor vanaf een willekeurige pagina — 3 minuten.", play_kind: "unwind", tags: ["reading", "quiet"], energy: 1 },
  { id: "pd_e61", title: "Maak een ‘moodboard’ in je notities-app met 6 plaatjes.", play_kind: "fun", tags: ["creative", "crafting"], energy: 2 },
  { id: "pd_e62", title: "Doe shadowboxing 2 min — geen spiegel, alleen gevoel.", play_kind: "fun", tags: ["sports", "active", "chill"], energy: 2 },
  { id: "pd_e63", title: "Schrijf een kort verhaal in SMS-stijl (max 160 tekens).", play_kind: "challenge", tags: ["writing", "competitive"], energy: 2, spice: "low" },
  { id: "pd_e64", title: "Zet één lamp anders: kleur of hoek — sfeer-test.", play_kind: "unwind", tags: ["homebody", "creative", "quiet"], energy: 1 },
  { id: "pd_e65", title: "Speel ‘guess the BPM’ bij een nummer — check daarna.", play_kind: "fun", tags: ["music", "games", "puzzles"], energy: 1 },
  { id: "pd_e66", title: "Maak ijsblokjes met fruit of kruiden voor later.", play_kind: "fun", tags: ["cooking", "creative", "chill"], energy: 1 },
  { id: "pd_e67", title: "Stadswandeling: één foto van texture of graffiti die je boeit.", play_kind: "fun", tags: ["outdoors", "photography", "creative"], energy: 2 },
  { id: "pd_e68", title: "Doe een ‘tabletop RPG’ solo: gooi dobbel, beschrijf scene.", play_kind: "fun", tags: ["games", "writing", "creative"], energy: 2 },
  { id: "pd_e69", title: "10 kleine luxes die je jezelf gunt zonder schuldgevoel — opschrijven.", play_kind: "unwind", tags: ["writing", "chill", "philosophy"], energy: 1 },
  { id: "pd_e70", title: "Foto macro: textuur van stof/hout/steen.", play_kind: "fun", tags: ["photography", "creative", "quiet"], energy: 1 },
  { id: "pd_e71", title: "Dans alleen je schouders 1 nummer lang.", play_kind: "fun", tags: ["dancing", "music", "chill"], energy: 1 },
  { id: "pd_e72", title: "Schrijf een ‘patch notes’ van je humeur v1.0 → v1.1.", play_kind: "fun", tags: ["writing", "games", "creative"], energy: 2 },
  { id: "pd_e73", title: "Plating: maak één bord alsof het een restaurantgang is — daarna gewoon opeten of opruimen.", play_kind: "fun", tags: ["creative", "cooking", "homebody"], energy: 2 },
  { id: "pd_e74", title: "Adem 4-4-4-4 vier cycli voor het openen van je laptop.", play_kind: "unwind", tags: ["quiet", "chill"], energy: 1 },
  { id: "pd_e75", title: "Eind-boss: kies 1 klein klusje en versla het in ≤8 min.", play_kind: "challenge", tags: ["competitive", "homebody"], energy: 2, spice: "medium" },
  { id: "pd_e76", title: "Ochtend-mini: 5 minuten daglicht op balkon of voor de deur.", play_kind: "unwind", tags: ["morning", "outdoors", "quiet"], energy: 1 },
  { id: "pd_e77", title: "Voor 10:00: één pagina lezen met koffie/thee, geen scroll.", play_kind: "unwind", tags: ["morning", "reading", "quiet"], energy: 1 },
  { id: "pd_e78", title: "Avond-modus: dim schermen, alleen warm licht 15 min.", play_kind: "unwind", tags: ["chill", "film", "quiet"], energy: 1 },
  { id: "pd_e79", title: "Lees één hoofdstuk manga (papier of legaal digitaal) — geen speedrun.", play_kind: "unwind", tags: ["manga", "reading", "quiet"], energy: 2 },
  { id: "pd_e80", title: "Kijk één aflevering anime, ondertitels aan, telefoon opzij.", play_kind: "fun", tags: ["anime", "film", "chill"], energy: 2 },
  { id: "pd_e81", title: "Teken één panel in ‘manga-stijl’ van je lunch.", play_kind: "fun", tags: ["manga", "creative", "writing"], energy: 2 },
  { id: "pd_e82", title: "Lees 10 pagina’s van een graphic novel of stripalbum.", play_kind: "unwind", tags: ["comics", "reading", "quiet"], energy: 2 },
  { id: "pd_e83", title: "Herstyle één plank, vensterbank of hoekje — timer 12 min.", play_kind: "fun", tags: ["decorating", "homebody", "creative"], energy: 2 },
  { id: "pd_e84", title: "Maak een moodboard (Pinterest of fysiek) voor één kamer.", play_kind: "fun", tags: ["decorating", "creative", "online_shopping"], energy: 2 },
  { id: "pd_e85", title: "Wandel door je huis en verplaats één ding voor beter licht.", play_kind: "unwind", tags: ["decorating", "quiet", "homebody"], energy: 1 },
  { id: "pd_e86", title: "Maak een wishlist van 5 dingen onder €25 — géén afrekenen.", play_kind: "fun", tags: ["online_shopping", "games", "chill"], energy: 1 },
  { id: "pd_e87", title: "Vergelijk 3 reviews van hetzelfde product — alleen lezen.", play_kind: "challenge", tags: ["online_shopping", "puzzles"], energy: 2, spice: "low" },
  { id: "pd_e88", title: "Schrijf 8 zinnen: wat betekent ‘goed leven’ voor jou vandaag?", play_kind: "unwind", tags: ["philosophy", "writing", "quiet"], energy: 2 },
  { id: "pd_e89", title: "Lees één korte tekst (blog/Stanford Encyclopedia) over een ethisch dilemma.", play_kind: "fun", tags: ["philosophy", "reading", "learning"], energy: 2 },
  { id: "pd_e90", title: "Stel één ‘socratische’ vraag hardop — en beantwoord die in 3 min.", play_kind: "challenge", tags: ["philosophy", "competitive", "quiet"], energy: 2, spice: "low" },
  { id: "pd_e91", title: "Luister max. 20 min true crime — daarna bewust stoppen, thee erbij.", play_kind: "unwind", tags: ["true_crime", "podcasts", "chill"], energy: 2 },
  { id: "pd_e92", title: "Los een mini ‘cold case’ puzzel uit een magazine of app (geen echte zaak stalken).", play_kind: "fun", tags: ["true_crime", "puzzles", "quiet"], energy: 2 },
  { id: "pd_e93", title: "Kijk één aflevering K-drama met snack — geen binge-knop.", play_kind: "fun", tags: ["kdrama", "film", "cooking"], energy: 2 },
  { id: "pd_e94", title: "Kies één documentaire ≤45 min over iets dat je niks uitstaat.", play_kind: "fun", tags: ["documentaries", "learning", "film"], energy: 2 },
  { id: "pd_e95", title: "Snuffel 15 min online op vintage/tweedehands — niets kopen.", play_kind: "fun", tags: ["thrifting", "online_shopping", "chill"], energy: 1 },
  { id: "pd_e96", title: "Leg 3 ‘vondsten’ uit huis die vintage vibes hebben — fotorei.", play_kind: "fun", tags: ["thrifting", "photography", "creative"], energy: 2 },
  { id: "pd_e97", title: "Kijk naar de maan of een heldere planeet — app mag, buiten 5 min.", play_kind: "unwind", tags: ["astronomy", "outdoors", "quiet"], energy: 1 },
  { id: "pd_e98", title: "Lees één Wikipedia-pagina over een historisch jaar dat je boeit.", play_kind: "fun", tags: ["history", "reading", "learning"], energy: 2 },
  { id: "pd_e99", title: "Vertel in 2 min iemand (of voice memo) een historisch feitje ‘als podcast’.", play_kind: "fun", tags: ["history", "social_light", "podcasts"], energy: 2 },
];
