-- Run this in Supabase Dashboard → SQL Editor if migration history is out of sync.
-- Marks migrations 002 through 065 as applied (e.g. after running 065 handmatig).
-- Skip any version that already exists (e.g. 001).

INSERT INTO supabase_migrations.schema_migrations (version, name, statements)
VALUES
  ('002_rls', '002_rls', '{}'),
  ('003_triggers', '003_triggers', '{}'),
  ('004_seed_quotes_sample', '004_seed_quotes_sample', '{}'),
  ('005_seed_quotes_full', '005_seed_quotes_full', '{}'),
  ('006_push_and_reports', '006_push_and_reports', '{}'),
  ('007_user_rollover_and_google_tokens', '007_user_rollover_and_google_tokens', '{}'),
  ('008_tasks_recurring_subtasks_snooze', '008_tasks_recurring_subtasks_snooze', '{}'),
  ('009_budget_settings', '009_budget_settings', '{}'),
  ('010_strategy_key_results', '010_strategy_key_results', '{}'),
  ('011_fix_rls_recursion', '011_fix_rls_recursion', '{}'),
  ('012_recurrence_monthly', '012_recurrence_monthly', '{}'),
  ('013_tasks_impact_urgency', '013_tasks_impact_urgency', '{}'),
  ('014_monthly_books', '014_monthly_books', '{}'),
  ('015_tasks_category_recurrence_weekdays', '015_tasks_category_recurrence_weekdays', '{}'),
  ('016_budget_currency_impulse_savings_status', '016_budget_currency_impulse_savings_status', '{}'),
  ('017_budget_period_contributions_impulse_recurring', '017_budget_period_contributions_impulse_recurring', '{}'),
  ('017_learning_growth_schema', '017_learning_growth_schema', '{}'),
  ('018_strategy_enhancements', '018_strategy_enhancements', '{}'),
  ('019_user_preferences_xp_analytics', '019_user_preferences_xp_analytics', '{}'),
  ('020_behavior_engine', '020_behavior_engine', '{}'),
  ('020_tasks_mental_social_load', '020_tasks_mental_social_load', '{}'),
  ('021_assistant_escalation_identity', '021_assistant_escalation_identity', '{}'),
  ('021_dcic_missions', '021_dcic_missions', '{}'),
  ('022_assistant_user_context_turn', '022_assistant_user_context_turn', '{}'),
  ('022_dcic_finance_state', '022_dcic_finance_state', '{}'),
  ('023_calendar_feed_token', '023_calendar_feed_token', '{}'),
  ('024_push_quiet_hours', '024_push_quiet_hours', '{}'),
  ('025_budget_payday_day', '025_budget_payday_day', '{}'),
  ('026_dcic_gamification_engine', '026_dcic_gamification_engine', '{}'),
  ('027_identity_engine', '027_identity_engine', '{}'),
  ('028_strategy_check_in', '028_strategy_check_in', '{}'),
  ('029_user_preferences_compact_ui', '029_user_preferences_compact_ui', '{}'),
  ('030_tasks_focus_required', '030_tasks_focus_required', '{}'),
  ('031_strategy_kr_checklist', '031_strategy_kr_checklist', '{}'),
  ('032_insights_daily_metrics_mission_events', '032_insights_daily_metrics_mission_events', '{}'),
  ('033_strategy_four_layers', '033_strategy_four_layers', '{}'),
  ('034_missions_performance_engine', '034_missions_performance_engine', '{}'),
  ('035_emotional_state_resistance', '035_emotional_state_resistance', '{}'),
  ('036_economy_chains_pressure', '036_economy_chains_pressure', '{}'),
  ('037_user_preferences_reduced_motion', '037_user_preferences_reduced_motion', '{}'),
  ('038_tasks_soft_delete', '038_tasks_soft_delete', '{}'),
  ('039_strategy_focus_archive_reason', '039_strategy_focus_archive_reason', '{}'),
  ('040_analytics_events', '040_analytics_events', '{}'),
  ('041_tasks_validation_type', '041_tasks_validation_type', '{}'),
  ('042_xp_events', '042_xp_events', '{}'),
  ('043_budget_entries_archive', '043_budget_entries_archive', '{}'),
  ('043_tasks_base_xp', '043_tasks_base_xp', '{}'),
  ('044_monthly_books_pages', '044_monthly_books_pages', '{}'),
  ('045_behavior_profile', '045_behavior_profile', '{}'),
  ('046_avoidance_tracker', '046_avoidance_tracker', '{}'),
  ('047_avoidance_forced_meta', '047_avoidance_forced_meta', '{}'),
  ('048_tasks_avoidance_tag', '048_tasks_avoidance_tag', '{}'),
  ('049_behavior_week_theme', '049_behavior_week_theme', '{}'),
  ('050_behavior_confrontation_mode', '050_behavior_confrontation_mode', '{}'),
  ('051_tasks_hobby_tag', '051_tasks_hobby_tag', '{}'),
  ('052_engine_controls_minimal_integrity_master_missions', '052_engine_controls_minimal_integrity_master_missions', '{}'),
  ('053_last_payday_date', '053_last_payday_date', '{}'),
  ('054_drop_quotes_table', '054_drop_quotes_table', '{}'),
  ('055_daily_state_mental_battery_load', '055_daily_state_mental_battery_load', '{}'),
  ('056_fase2_tasks_difficulty_missions_focus_social', '056_fase2_tasks_difficulty_missions_focus_social', '{}'),
  ('057_performance_rank_task_events_behaviour_log', '057_performance_rank_task_events_behaviour_log', '{}'),
  ('058_fase4_daily_obligation_penalty', '058_fase4_daily_obligation_penalty', '{}'),
  ('059_fase5_decision_cost_focus_consumed', '059_fase5_decision_cost_focus_consumed', '{}'),
  ('060_fase6_recovery_rest_day', '060_fase6_recovery_rest_day', '{}'),
  ('061_fase7_weekly_performance_index_patterns', '061_fase7_weekly_performance_index_patterns', '{}'),
  ('062_fase8_progression_rank_ladder', '062_fase8_progression_rank_ladder', '{}'),
  ('063_fase9_prime_window', '063_fase9_prime_window', '{}'),
  ('064_fase10_weekly_behavior_index_budget', '064_fase10_weekly_behavior_index_budget', '{}'),
  ('065_pending_xp_notifications', '065_pending_xp_notifications', '{}'),
  ('066_auto_missions_unique_title_per_day', '066_auto_missions_unique_title_per_day', '{}'),
  ('067_gevaarlijke_modules', '067_gevaarlijke_modules', '{}')
ON CONFLICT (version) DO NOTHING;
