/**
 * Parses 365_Philosophical_Quotes_Structured.txt and generates SQL to seed public.quotes.
 * Output: supabase/migrations/005_seed_quotes_full.sql
 *
 * Run: node scripts/seed-quotes.js
 * Then run migration 005 in Supabase (or run migrations in order).
 */

const fs = require("fs");
const path = require("path");

const inputPath = path.join(__dirname, "..", "365_Philosophical_Quotes_Structured.txt");
const outputPath = path.join(__dirname, "..", "supabase", "migrations", "005_seed_quotes_full.sql");

function escapeSql(str) {
  if (str == null) return "NULL";
  return "'" + String(str).replace(/'/g, "''").replace(/\n/g, " ").replace(/\r/g, "") + "'";
}

const raw = fs.readFileSync(inputPath, "utf8");
const blocks = raw.split(/\nid: /).filter(Boolean);

const rows = [];
for (const block of blocks) {
  const firstLine = block.startsWith("id:") ? block : "id: " + block;
  const idMatch = firstLine.match(/^id:\s*(\d+)/);
  if (!idMatch) continue;
  const id = parseInt(idMatch[1], 10);
  const nameMatch = firstLine.match(/name:\s*(.+?)\s+era:/);
  const name = nameMatch ? nameMatch[1].trim() : "";
  const eraMatch = firstLine.match(/era:\s*(.+?)\s+quote:/);
  const era = eraMatch ? eraMatch[1].trim() : "";
  const quotePart = firstLine.replace(/^[\s\S]*?quote:\s*/, "").replace(/\n/g, " ").replace(/\s+/g, " ").trim();
  const onMatch = quotePart.match(/^On\s+([^:]+):\s*(.+)$/);
  let topic = "";
  let quoteText = quotePart;
  if (onMatch) {
    topic = onMatch[1].trim();
    quoteText = onMatch[2].trim().replace(/\s+/g, " ");
  }
  if (id >= 1 && id <= 365) rows.push({ id, author_name: name, era, topic, quote_text: quoteText });
}

rows.sort((a, b) => a.id - b.id);
// Dedupe by id (keep first)
const seen = new Set();
const unique = rows.filter((r) => {
  if (seen.has(r.id)) return false;
  seen.add(r.id);
  return true;
});

const values = unique
  .map(
    (r) =>
      `(${r.id}, ${escapeSql(r.author_name)}, ${escapeSql(r.era)}, ${escapeSql(r.topic)}, ${escapeSql(r.quote_text)})`
  )
  .join(",\n");

const sql = `-- NEUROHQ — Full quotes seed (generated by scripts/seed-quotes.js)
insert into public.quotes (id, author_name, era, topic, quote_text) values
${values}
on conflict (id) do update set
  author_name = excluded.author_name,
  era = excluded.era,
  topic = excluded.topic,
  quote_text = excluded.quote_text;
`;

fs.writeFileSync(outputPath, sql, "utf8");
console.log("Wrote", outputPath, "with", unique.length, "quotes.");
console.log("Run this migration in Supabase after 004_seed_quotes_sample.sql (or replace 004 with this).");
console.log("Or run migrations in order: 001 -> 002 -> 003 -> 005 (skip 004 if using 005).");