-- Push usage tracking (max 3/day) and weekly reality reports storage

-- 1. Push sent tracking on users
alter table public.users
  add column if not exists push_sent_count smallint default 0,
  add column if not exists push_sent_date date;

-- 2. Weekly reality reports (generated by cron)
create table if not exists public.reality_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  week_start date not null,
  week_end date not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(user_id, week_start)
);

create index if not exists idx_reality_reports_user_week on public.reality_reports(user_id, week_start);

alter table public.reality_reports enable row level security;

create policy "users_own_reality_reports" on public.reality_reports for all using (auth.uid() = user_id);
create policy "admin_read_reality_reports" on public.reality_reports for select using (
  exists (select 1 from public.users where id = auth.uid() and role = 'admin')
);
